version: '3.3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE_NAME: mydatabase
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  db-data: